#include "Vbasicgates.h"    // Include header generated by Verilator
#include "verilated.h"

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vbasicgates* tb = new Vbasicgates;

    while (!Verilated::gotFinish()) {
        tb->eval();  // Evaluate model
    }

    delete tb;
    return 0;
}