#include "Vbasicgates.h"    // Include header generated by Verilator
#include "verilated.h"
#include <verilated_vcd_c.h>
double sc_time_stamp() { return 0; }
int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vbasicgates *tb = new Vbasicgates;
    Verilated::traceEverOn(true);  // Verilator must compute traced signals
    VerilatedVcdC* tfp = new VerilatedVcdC;
    tb->trace(tfp, 99);
    tfp->open("waveform.vcd");
    while (!Verilated::gotFinish()) {
        tb->eval();  // Evaluate model
        tfp->dump(sc_time_stamp());
        
    }
    delete tb;
    return 0;
}